name: 29938_test

on:
  push:
    branches: [ main ]

env:
  # ne pisat v /Users/runner.
  RUNNER_TOOL_CACHE: /Users/timzav/Documents/FERI_/SA/Vaja4/actions-runner/_tool
  AGENT_TOOLSDIRECTORY: /Users/timzav/Documents/FERI_/SA/Vaja4/actions-runner/_tool

jobs:
  preveri-teste:
    runs-on: self-hosted

    steps:
      # presena iz gita na runerja
      - uses: actions/checkout@v4

      # obstaja test?
      - name: Preveri obstoj testov
        run: |
          rm -f napaka.txt
          exec 2> napaka.txt

          if [ ! -f test.sh ]; then
            echo "Testi ne obstajajo" >&2
          fi

      # shrani napaka.txt kot artefakt
      - name: Upload artefakt
        uses: actions/upload-artifact@v4
        with:
          name: napaka
          path: napaka.txt

  zazeni-teste:
    # ce prvi uspe se ta zazene
    needs: preveri-teste
    runs-on: self-hosted

    # matrix = dva zaporedna runa na istem env
    strategy:
      matrix:
        test_run: ['1', '2']

    steps:
      # download kot zgoraj
      - uses: actions/checkout@v4

      # download artefakt iz prvega joba
      - name: Download artefakt
        uses: actions/download-artifact@v4
        with:
          name: napaka

      # preveri vsebino artifakta
      - name: Preveri napako
        run: |
          if [ -s napaka.txt ]; then
            cat napaka.txt
            exit 1
          fi

      # python environment za teste (matrix)

      # odvisnosti
      - name: Install deps
        run: python3 -m pip install -r requirements.txt

      - name: matrix zagon
        run: echo "Matrix run ${{ matrix.test_run }}"

      # run testna skripta
      - name: Run test
        run: |
          chmod +x test.sh
          ./test.sh